repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        files: '.*\.go'
      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
      - id: staticcheck
        name: staticcheck
        entry: staticcheck ./...
        language: system
        pass_filenames: false
