name: Changelog

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate changelog
        run: |
          last_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          git log --pretty=format:'* %s (%h)' ${last_tag}..HEAD > CHANGELOG.md
      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: CHANGELOG.md

