name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.22']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Verify formatting
        run: |
          fmt_res=$(gofmt -l .)
          if [ -n "$fmt_res" ]; then
            echo "$fmt_res" && exit 1
          fi
      - name: Go vet
        run: go vet ./...
      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: latest
      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.out
